spring:
  application:
    name: shoppingMall
  profiles:
    active: local
  thymeleaf:
    cache: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
    rest:
      default-page-size: 10
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB # 단일 파일 최대
      max-request-size: 20MB # 여러 파일 합계

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    try-it-out-enabled: true

jwt:
  secret: "s5TTgY4zdXRTZ58o/UdClxBqf4SKi3Hn11obMgLdP5w="
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

file:
  upload:
    product-path: products
    allowed-extensions: jpg,jpeg,png,webp

image:
  resize:
    max-width: 1200
    quality: 0.85
  thumbnail:
    main-size: 300
    slider-size: 100

server:
  port: 8080

logging:
  level:
    root: INFO
