spring:
  datasource:
    # H2로 쓰고 싶을 때는 아래 주석을 켜고, MySQL 쪽은 끄면 됨
    # url: jdbc:h2:mem:testdb
    # username: sa
    # password:
    # driver-class-name: org.h2.Driver

    url: jdbc:mysql://localhost:3306/shop?createDatabaseIfNotExist=true
    username: root
    password: passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
#  servlet:
#    multipart:
#      max-file-size: 5MB # 단일 파일 최대
#      max-request-size: 20MB # 여러 파일 합계

file:
  upload:
    base-path: C:/uploads

logging:
  level:
    root: INFO
    com.example.elicesecondproject: DEBUG
