spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team1shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: team1
    password: passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 운영환경은 validate
    properties:
      hibernate:
        show_sql: true
      defer-datasource-initialization: true
      sql:
        init:
          mode: always
          encoding: UTF-8
file:
  upload:
    base-path: /home/gitlab-runner/uploads

logging:
  level:
    root: INFO
    com.example.elicesecondproject: DEBUG