spring:
  profiles:
    active: local
  application:
    name: shoppingMall
  thymeleaf:
    cache: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  springdoc:
    api-docs:
      enabled: true
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui
      operations-sorter: method
      tags-sorter: alpha